method: grid  # grid, bayes, random
metric:
  name: test_loss
  goal: minimize
parameters:
  learning_rate:
    values: [0.001]
  batch_size:
    values: [100]
  num_epochs:
    values: [2000]
  weight_decay:
    values: [1e-2,5e-1, 1e-1, 1, 10]
  gradient_clipping_max_norm:
    values: [1e4]
  scheduler_patience:
    values: [2000]