method: grid  # grid, bayes, random
metric:
  name: test_loss
  goal: minimize
parameters:
  model:
    values: ['gnn']
  dataset_folder:
    values: ['data/long_rollouts_100_max_amplitude_80_policy_harmonic_inputs_2']
  node_hidden_features:
    values: [50]
  learning_rate:
    values: [1e-1,1e-2, 1e-3, 1e-4, 1e-5]
  num_epochs:
    values: [100]