method: grid  # grid, bayes, random
metric:
  name: test_loss
  goal: minimize
parameters:
  model:
    values: ['gnn']
  use_ids:
    values: [True, False]
  use_alpha:
    values: [True, False]
  dataset_folder:
    values: ['data/mass_100g_no_kick']