method: grid  # grid, bayes, random
metric:
  name: avg_tip_open_loop_rmse
  goal: minimize
parameters:
  model:
    values: ['gnn']
  dataset_folder:
    values: ['data/mass_100g_harmonic',
             'data/mass_100g_harmonic_short']
  num_epochs:
    values: [2000]
  