method: grid  # grid, bayes, random
metric:
  name: test_loss
  goal: minimize
parameters:
  model:
    values: ['gnn']
  dataset_folder:
    values: ['data/mass_500g_harmonic_ssm']
  node_hidden_features:
    values: [50]
    