method: random  # grid, bayes, random
metric:
  name: test_loss
  goal: minimize
parameters:
  learning_rate:
    values: [1e-3]
  batch_size:
    values: [200]
  num_epochs:
    values: [2000]
  weight_decay:
    values: [0.0]
  gradient_clipping_max_norm:
    values: [1e9]
  scheduler_patience:
    values: [100]