method: grid  # grid, bayes, random
metric:
  name: avg_tip_open_loop_rmse
  goal: minimize
parameters:
  model:
    values: ['gnn']
  dataset_folder:
    values: ['data/real-350-1']
  num_epochs:
    values: [1000]
  weight_decay:
    values: [1e-7]
  