method: grid  # grid, bayes, random
metric:
  name: test_loss
  goal: minimize
parameters:
  model:
    values: ['mlp']
  dataset_folder:
    values: ['data/mass_100g_harmonic']
  shuffle:
    values: [False]
  mlp_num_hidden_layers:
    values: [4, 8]
  mlp_hidden_features:
    values: [150, 300]