method: grid  # grid, bayes, random
metric:
  name: avg_tip_open_loop_rmse
  goal: minimize
parameters:
  model:
    values: ['gnn']
  dataset_folder:
    values: ['data/long_rollouts_100_max_amplitude_80_policy_harmonic_inputs_2']
  num_epochs:
    values: [2000]
  weight_decay:
    values: [1e-7, 1e-8, 1e-9]
  