method: grid  # grid, bayes, random
metric:
  name: avg_tip_open_loop_rmse
  goal: minimize
parameters:
  model:
    values: ['gnn']
  dataset_folder:
    values: ['data/overfit-mn-1e1-short']
  node_hidden_features:
    values: [50]
  weight_decay:
    values: [1e-9]
  num_epochs:
    values: [10000]