method: grid  # grid, bayes, random
metric:
  name: test_loss
  goal: minimize
parameters:
  model:
    values: ['gnn']
  dataset_folder:
    values: ['data/mass_100g_harmonic']
  node_hidden_features:
    values: [25, 50, 100, 150, 200, 400]
