method: grid  # grid, bayes, random
metric:
  name: test_loss
  goal: minimize
parameters:
  model:
    values: ['gnn']
  dataset_folder:
    values: ['data/mass_100g_harmonic']
  encode_nodes:
    values: [True, False]
  encode_inputs:
    values: [True, False]
  num_epochs:
    values: [500]
