method: grid  # grid, bayes, random
metric:
  name: test_loss
  goal: minimize
parameters:
  model:
    values: ['gnn']
  dataset_folder:
    values: ['data/mass_100g_harmonic']
  batch_norm:
    values: [True, False]
  layer_norm:
    values: [True, False]