method: grid  # grid, bayes, random
metric:
  name: test_loss
  goal: minimize
parameters:
  model:
    values: ['gnn']
  dataset_folder:
    values: ['data/overfit-mn-1e1']
  node_hidden_features:
    values: [50]
  num_epochs:
    values: [1000]
  weight_decay:
    values: [1e-3, 1e-2, 1e-1, 1e0, 1e1]