method: grid  # grid, bayes, random
metric:
  name: test_loss
  goal: minimize
parameters:
  model:
    values: ['gnn']
  dataset_folder:
    values: ['data/overfit-mn-1e1']
  node_hidden_features:
    values: [50, 100, 150]
  num_epochs:
    values: [1000]