method: grid  # grid, bayes, random
metric:
  name: test_loss
  goal: minimize
parameters:
  model:
    values: ['gnn']
  dataset_folder:
    values: ['data/overfit-mn-1e1']
  node_hidden_features:
    values: [50]
  num_epochs:
    values: [1000]
  weight_decay:
    values: [1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9]